@localhost=localhost:4004/odata/v4/main
@id=6efc7453-7c49-4773-825a-0dcaaf350f33

GET http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

###

POST http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

{}

###

PUT http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json

{}

###

DELETE http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json
